-- AlterTable
ALTER TABLE "Video" ADD COLUMN     "dislike" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "like" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "views" INTEGER[] DEFAULT ARRAY[]::INTEGER[];
